sessionStorage.removeItem('daymark_token');
const state = { mode: 'login', token: sessionStorage.getItem('daymark_token'), data: null };
const $ = (id) => document.getElementById(id);
const sectors = {
  daily: { label: 'Daily schedule', kicker: 'Build the rhythm', title: 'Win the day before it gets loud.', copy: 'A practical sequence for protecting your best hours and ending the day with proof.', color: 'lime', items: [['Morning reset', 'Start with water, movement, and a written priority.'], ['Deep work block', '90 minutes of distraction-free CS core practice.'], ['Problem set', 'Three deliberate problems, reviewed without rushing.'], ['Close the loop', 'Record the lesson and choose tomorrow’s first move.']] },
  month: { label: 'Month-end goal', kicker: 'One clear finish line', title: 'Give this month a shape.', copy: 'Choose a result that is specific enough to recognize and meaningful enough to pull you forward.', color: 'orange', items: [['Define the finish line', 'Write the one result that makes this month successful.'], ['Collect evidence', 'Link work, projects, or notes that prove movement.'], ['Review every Sunday', 'Adjust the plan before the month adjusts it for you.']] },
  temporary: { label: 'Temporary goals', kicker: 'Short campaigns', title: 'Make space for what matters now.', copy: 'Temporary goals are focused campaigns with an expiry date. Keep them visible, small, and honest.', color: 'blue', items: [['Name the campaign', 'Give the current sprint a clear title and end date.'], ['Choose the next action', 'Make progress so obvious that starting feels easy.'], ['Retire or renew', 'At the end date, close it or consciously extend it.']] },
  longterm: { label: 'Long-term goals', kicker: 'The direction', title: 'Keep the horizon in view.', copy: 'Long-term goals are a compass, not a daily scoreboard. Revisit them often enough to keep today meaningful.', color: 'ink', items: [['Write the direction', 'Describe the person, craft, or life you are building toward.'], ['Pick a yearly milestone', 'Translate the direction into one measurable checkpoint.'], ['Protect the identity', 'Choose the weekly behavior that makes it inevitable.']] }
};
async function api(path, options = {}) { const response = await fetch(`/api${path}`, { ...options, headers: { 'Content-Type': 'application/json', ...(state.token ? { Authorization: `Bearer ${state.token}` } : {}) } }); const body = await response.json().catch(() => ({})); if (!response.ok) throw new Error(body.detail || 'Something went wrong'); return body; }
function formatDateHeader(dateString = new Date().toISOString().slice(0, 10)) { const date = new Date(`${dateString}T00:00:00`); return date.toLocaleDateString('en-GB', { weekday: 'long', day: 'numeric', month: 'long', year: 'numeric' }); }
function syncPageHeader() { const dateLabel = state.data?.date_label || formatDateHeader(); const pageKicker = $('page-kicker'); if (pageKicker) pageKicker.textContent = dateLabel; }
function setAuthMode(mode) { state.mode = mode; document.querySelectorAll('.tab').forEach((tab) => tab.classList.toggle('active', tab.dataset.auth === mode)); $('name-field').classList.toggle('hidden', mode !== 'register'); $('auth-kicker').textContent = mode === 'login' ? 'Welcome back' : 'Start your run'; $('auth-title').textContent = mode === 'login' ? 'Pick up where you left off.' : 'Build a better baseline.'; $('auth-submit').innerHTML = mode === 'login' ? 'Enter dashboard <span>↗</span>' : 'Create my account <span>↗</span>'; $('auth-message').textContent = ''; }
async function submitAuth(event) { event.preventDefault(); const payload = { email: $('email').value, password: $('password').value }; if (state.mode === 'register') payload.name = $('name').value; $('auth-submit').disabled = true; try { const result = await api(state.mode === 'login' ? '/auth/login' : '/auth/register', { method: 'POST', body: JSON.stringify(payload) }); state.token = result.token; sessionStorage.setItem('daymark_token', state.token); await loadDashboard(); } catch (error) { $('auth-message').textContent = error.message; } finally { $('auth-submit').disabled = false; } }
function progressPercent(items) { return items.length ? Math.round(items.filter((item) => item.done).length / items.length * 100) : 0; }
function renderHome() { const { tasks, sectors: progress, days_complete: days, streak } = state.data; const today = progressPercent(tasks); $('page-container').innerHTML = `<section class="hero-row"><div><p class="eyebrow accent">Your operating system</p><h2>Make progress<br><em>visible.</em></h2><p class="muted hero-copy">Four perspectives, one honest signal: are your daily actions moving your bigger life forward?</p></div><div class="progress-orbit"><div class="orbit-ring"><strong>${Math.round((today + progressPercent(Object.values(progress).flat())) / 2)}%</strong><span>overall pulse</span></div><svg viewBox="0 0 160 160"><circle class="orbit-track" cx="80" cy="80" r="68"></circle><circle class="orbit-progress" style="stroke-dashoffset:${427.3 - (427.3 * today / 100)}" cx="80" cy="80" r="68"></circle></svg></div></section><section class="stat-grid"><article class="stat-card paper"><span class="stat-label">Today</span><strong>${today}%</strong><small>daily schedule complete</small></article><article class="stat-card ink"><span class="stat-label">Current streak</span><strong>${streak} days</strong><small>your consistency signal</small></article><article class="stat-card lime"><span class="stat-label">Days complete</span><strong>${days} / 31</strong><small>the bigger picture</small></article></section><section class="sector-grid">${Object.entries(sectors).map(([key, sector]) => { const percent = progressPercent(progress[key] || []); return `<a class="sector-card ${sector.color}" href="#${key}"><span class="sector-index">0${Object.keys(sectors).indexOf(key) + 1}</span><div><p class="eyebrow">${sector.label}</p><h3>${sector.title}</h3><p>${sector.copy}</p></div><div class="sector-meter"><span style="width:${percent}%"></span></div><strong>${percent}%</strong><span class="arrow">↗</span></a>`; }).join('')}</section><section class="calendar-panel runway"><div class="section-head"><div><p class="eyebrow">Your runway</p><h3>31-day map</h3></div><span class="legend"><i></i> complete</span></div><div class="day-grid">${Array.from({ length: 31 }, (_, index) => `<div class="day-cell ${index < days ? 'complete' : ''} ${index === state.data.day - 1 ? 'current' : ''}">${String(index + 1).padStart(2, '0')}</div>`).join('')}</div></section>`; }
function renderDaily() { const tasks = state.data.daily_tasks || []; const completed = tasks.filter((task) => task.done).length; $('page-container').innerHTML = `<section class="daily-hero"><div><p class="eyebrow">${state.data.date_label}</p><h2>Shape the day<br><em>around what matters.</em></h2><p class="muted hero-copy">Add the work that deserves your attention, give it a reason, and let the list stay honest.</p></div><div class="daily-date"><span>${new Date(`${state.data.date}T00:00:00`).toLocaleString('en', { month: 'short' }).toUpperCase()}</span><strong>${new Date(`${state.data.date}T00:00:00`).getDate()}</strong><small>${new Date(`${state.data.date}T00:00:00`).getFullYear()}</small></div></section><section class="daily-layout"><div class="daily-planner"><div class="section-head"><div><p class="eyebrow">Today’s schedule</p><h3>${completed} of ${tasks.length} complete</h3></div><span class="completion-pill">${progressPercent(tasks)}%</span></div><div class="task-list daily-task-list">${tasks.length ? tasks.map((task) => `<article class="daily-task ${task.done ? 'done' : ''}"><button class="task-check" data-daily-task="${task.id}" aria-label="Complete ${task.name}">${task.done ? '✓' : ''}</button><div class="daily-task-content"><div class="daily-task-top"><span class="task-title">${escapeHtml(task.name)}</span><span class="task-type">${escapeHtml(task.type)}</span></div><p>${escapeHtml(task.motive)}</p><span class="task-time">◷ ${escapeHtml(task.time)}</span></div><button class="remove-task" data-remove-task="${task.id}" aria-label="Remove ${task.name}">×</button></article>`).join('') : '<div class="empty-day">Your schedule is clear. Add one meaningful task to begin.</div>'}</div></div><aside class="add-task-card"><p class="eyebrow">Add a task</p><h3>Give your time a job.</h3><form id="daily-task-form"><label>Task name<input name="name" required placeholder="e.g. Build the API route"></label><label>Type<select name="type"><option>Deep work</option><option>Study</option><option>Health</option><option>Personal</option><option>Admin</option></select></label><div class="form-split"><label>Time<input name="time" required placeholder="09:00 - 10:30"></label><label>Motive<input name="motive" required placeholder="Why it matters"></label></div><button class="button button-dark" type="submit">Add to schedule <span>+</span></button><p id="daily-message" class="form-message"></p></form></aside></section>`; bindDailyButtons(); renderDailyAnalysis(); }
function renderDailyAnalysis() { const analysis = state.data.analysis; const history = analysis.days.slice(0, 8).map((day) => `<div class="analysis-day"><span>${day.task_date.slice(8)}</span><div><i style="width:${day.total ? Math.round(day.completed / day.total * 100) : 0}%"></i></div><small>${day.completed}/${day.total}</small></div>`).join(''); $('page-container').insertAdjacentHTML('beforeend', `<section class="daily-analysis"><div class="analysis-heading"><div><p class="eyebrow">${analysis.month} review</p><h3>Your month in motion</h3></div><span class="analysis-rate">${analysis.completion_rate}%</span></div><div class="analysis-stats"><div><strong>${analysis.total_tasks}</strong><small>tasks planned</small></div><div><strong>${analysis.completed_tasks}</strong><small>tasks complete</small></div><div><strong>${analysis.active_days}</strong><small>active days</small></div></div><div class="analysis-history">${history || '<p class="empty-day">Your daily history will appear here as you plan and complete tasks.</p>'}</div></section>`); }
function escapeHtml(value) { return String(value).replace(/[&<>'"]/g, (character) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#39;', '"': '&quot;' }[character])); }
function pageFrame(key, items) { const sector = sectors[key]; const saved = state.data.sectors[key] || []; const rows = key === 'daily' ? items : sector.items.map((item, index) => ({ title: item[0], copy: item[1], done: Boolean(saved[index]?.done), sector: key, task: index })); const percent = progressPercent(rows); return `<section class="sector-hero ${sector.color}"><div><p class="eyebrow">${sector.kicker}</p><h2>${sector.title}</h2><p class="muted hero-copy">${sector.copy}</p></div><div class="big-percent"><strong>${percent}%</strong><span>complete</span></div></section><section class="sector-layout"><div class="sector-detail"><div class="section-head"><div><p class="eyebrow">${sector.label}</p><h3>Next meaningful moves</h3></div><span class="completion-pill">${rows.filter((row) => row.done).length} / ${rows.length}</span></div><div class="task-list">${rows.map((row) => `<div class="task-row ${row.done ? 'done' : ''}"><button class="task-check" data-task="${row.task}" data-sector="${row.sector || 'daily'}">${row.done ? '✓' : ''}</button><div><span class="task-title">${row.title}</span><small class="task-description">${row.copy}</small></div><span class="task-meta">${row.done ? 'complete' : 'open'}</span></div>`).join('')}</div></div><aside class="note-panel ${sector.color}"><p class="eyebrow">Working note</p><h3>Give it a sentence.</h3><textarea id="sector-note" rows="7" placeholder="What will make this easier to begin?"></textarea><button class="button button-dark" data-note="${key}">Save note <span>↗</span></button><p id="page-message" class="form-message"></p></aside></section>`; }
function renderPage() { syncPageHeader(); const page = location.hash.slice(1) || 'home'; document.querySelectorAll('.nav-link').forEach((link) => link.classList.toggle('active', link.dataset.page === page)); if (page === 'home') renderHome(); else if (page === 'daily') renderDaily(); else if (page === 'month') renderMonth(); else if (page === 'temporary' || page === 'longterm') renderTimedGoals(page); else if (sectors[page]) { $('page-container').innerHTML = pageFrame(page, []); bindSectorButtons(); } else { location.hash = '#home'; } }
function bindTaskButtons() { document.querySelectorAll('.task-check').forEach((button) => button.addEventListener('click', () => toggleTask(Number(button.dataset.task)))); document.querySelector('[data-note]')?.addEventListener('click', () => saveNote(document.querySelector('[data-note]').dataset.note)); }
function bindDailyButtons() { document.querySelectorAll('[data-daily-task]').forEach((button) => button.addEventListener('click', () => toggleDailyTask(Number(button.dataset.dailyTask)))); document.querySelectorAll('[data-remove-task]').forEach((button) => button.addEventListener('click', () => removeDailyTask(Number(button.dataset.removeTask)))); $('daily-task-form').addEventListener('submit', addDailyTask); }
function renderMonth() { const goals = state.data.monthly_goals || []; $('page-container').innerHTML = `<section class="month-hero"><div><p class="eyebrow">One clear finish line</p><h2>Give this month<br><em>a shape.</em></h2><p class="muted hero-copy">Create meaningful outcomes, then turn each one into a short visible queue of next moves.</p></div><div class="month-stamp"><span>${new Date().toLocaleString('en', { month: 'short' }).toUpperCase()}</span><strong>${new Date().getFullYear()}</strong></div></section><section class="month-toolbar"><div><p class="eyebrow">Monthly goals</p><h3>${goals.length} goal${goals.length === 1 ? '' : 's'} in motion</h3></div><button class="button button-dark" id="show-goal-form">New goal <span>+</span></button></section><form id="monthly-goal-form" class="goal-create-form hidden"><label>Goal title<input name="title" required placeholder="e.g. Ship my portfolio project"></label><label>Why this matters<input name="motive" placeholder="The result I want by month end"></label><button class="button button-dark" type="submit">Create monthly goal <span>↗</span></button><p id="month-message" class="form-message"></p></form><section class="goal-stack">${goals.length ? goals.map(monthGoalCard).join('') : '<div class="empty-goals">No monthly goals yet. Start with one finish line that would make this month feel different.</div>'}</section>`; bindMonthButtons(); }
function monthGoalCard(goal) { const visible = goal.expanded ? goal.subgoals : goal.subgoals.slice(0, 5); const completed = goal.subgoals.filter((item) => item.done).length; const percent = goal.subgoals.length ? Math.round(completed / goal.subgoals.length * 100) : 0; const totalLabel = goal.subgoals.length > 5 ? `${visible.length} / ${goal.subgoals.length}` : `${goal.subgoals.length}`; return `<article class="month-goal-card"><div class="goal-card-head"><div><span class="goal-number">GOAL 0${goal.id} · <b class="status-${goal.status}">${goal.status}</b></span><h3>${escapeHtml(goal.title)}</h3><p>${escapeHtml(goal.motive || 'A result worth showing up for.')}</p></div><div class="goal-card-actions"><strong>${percent}%</strong><button class="remove-task" data-remove-goal="${goal.id}" aria-label="Remove goal">×</button></div></div><div class="goal-meter"><span style="width:${percent}%"></span></div><div class="subgoal-heading"><span>${goal.expanded ? 'All moves' : 'Next moves'}</span><small>${completed} complete · ${totalLabel} total</small></div><div class="subgoal-list">${visible.length ? visible.map((item) => `<div class="subgoal-row"><button class="task-check" data-subgoal="${item.id}" aria-label="Complete ${escapeHtml(item.title)}"></button><span>${escapeHtml(item.title)}</span><div class="subgoal-actions"><button class="mini-action" data-edit-subgoal="${item.id}" aria-label="Edit subgoal">Edit</button><button class="mini-action" data-move-subgoal="${item.id}" data-direction="-1" aria-label="Move subgoal up">↑</button><button class="mini-action" data-move-subgoal="${item.id}" data-direction="1" aria-label="Move subgoal down">↓</button><button class="remove-task" data-remove-subgoal="${item.id}" aria-label="Remove subgoal">×</button></div></div>`).join('') : '<p class="subgoal-empty">All visible moves are complete. Add the next one to keep the queue moving.</p>'}</div>${goal.subgoals.length > 5 ? `<button class="subtask-toggle" data-toggle-subgoal-list="${goal.id}" type="button">${goal.expanded ? 'Show fewer' : `Show all (${goal.subgoals.length})`}</button>` : ''}<form class="subgoal-form" data-goal="${goal.id}"><input name="title" required placeholder="Add a subgoal"><button type="submit" aria-label="Add subgoal">+</button></form></article>`; }
function bindMonthButtons() { $('show-goal-form').addEventListener('click', () => $('monthly-goal-form').classList.toggle('hidden')); $('monthly-goal-form').addEventListener('submit', addMonthlyGoal); document.querySelectorAll('[data-remove-goal]').forEach((button) => button.addEventListener('click', () => removeMonthlyGoal(Number(button.dataset.removeGoal)))); document.querySelectorAll('[data-subgoal]').forEach((button) => button.addEventListener('click', () => toggleSubgoal(Number(button.dataset.subgoal)))); document.querySelectorAll('[data-remove-subgoal]').forEach((button) => button.addEventListener('click', () => removeSubgoal(Number(button.dataset.removeSubgoal)))); document.querySelectorAll('[data-edit-subgoal]').forEach((button) => button.addEventListener('click', () => editSubgoal(Number(button.dataset.editSubgoal)))); document.querySelectorAll('[data-move-subgoal]').forEach((button) => button.addEventListener('click', () => moveSubgoal(Number(button.dataset.moveSubgoal), Number(button.dataset.direction)))); document.querySelectorAll('[data-toggle-subgoal-list]').forEach((button) => button.addEventListener('click', () => toggleGoalSubtaskList(Number(button.dataset.toggleSubgoalList)))); document.querySelectorAll('[data-toggle-completed-month]').forEach((button) => button.addEventListener('click', () => toggleCompletedMonth(Number(button.dataset.toggleCompletedMonth)))); document.querySelectorAll('.subgoal-form').forEach((form) => form.addEventListener('submit', addSubgoal)); }
function formatRemaining(seconds) { const days = Math.floor(seconds / 86400); const hours = Math.floor((seconds % 86400) / 3600); const minutes = Math.floor((seconds % 3600) / 60); return days ? `${days}d ${hours}h left` : `${hours}h ${minutes}m left`; }
function renderTimedGoals(kind) { const timed = (state.data.timed_goals || []).filter((goal) => goal.kind === kind); const sector = sectors[kind]; $('page-container').innerHTML = `<section class="timed-hero ${sector.color}"><div><p class="eyebrow">${kind === 'temporary' ? 'Short campaigns' : 'The direction'}</p><h2>${kind === 'temporary' ? 'Make space for what matters now.' : 'Keep the horizon in view.'}</h2><p class="muted hero-copy">${kind === 'temporary' ? 'Give focused work a deadline and a clear finish.' : 'Put a date on the direction so it keeps moving.'}</p></div><div class="timed-clock"><span>${timed.length}</span><small>active goals</small></div></section><section class="timed-toolbar"><div><p class="eyebrow">${sector.label}</p><h3>Goals with a clock</h3></div><button class="button button-dark" id="show-timed-form">New goal <span>+</span></button></section><form id="timed-goal-form" class="timed-create-form hidden"><label>Goal title<input name="title" required placeholder="What are you finishing?"></label><label>Motive<input name="motive" placeholder="Why this matters"></label><label>Complete by<input name="deadline" type="datetime-local" required></label><button class="button button-dark" type="submit">Set the clock <span>↗</span></button><p id="timed-message" class="form-message"></p></form><section class="timed-goal-grid">${timed.length ? timed.map(timedGoalCard).join('') : '<div class="empty-goals">No timed goals yet. Set one deadline and make the remaining time visible.</div>'}</section>`; bindTimedButtons(kind); }
function timedGoalCard(goal) { const subtasks = goal.subtasks || []; const visible = goal.expanded ? subtasks : subtasks.slice(0, 5); return `<article class="timed-goal-card ${goal.status}"><div class="timed-card-top"><span class="goal-number">${goal.status}</span><button class="remove-task" data-remove-timed="${goal.id}" aria-label="Remove goal">×</button></div><h3>${escapeHtml(goal.title)}</h3><p>${escapeHtml(goal.motive || 'A goal worth protecting.')}</p><div class="countdown ${goal.status}">${goal.done ? 'Completed' : goal.status === 'overdue' ? 'Overdue' : formatRemaining(goal.remaining_seconds)}</div><div class="timed-card-actions"><button class="button ${goal.done ? 'button-light' : 'button-dark'}" data-toggle-timed="${goal.id}">${goal.done ? 'Reopen goal' : 'Mark complete'} <span>✓</span></button><small>${goal.elapsed_percent}% of planned time used</small></div><div class="subtask-heading"><span>Subtasks</span><small>${subtasks.filter((item) => item.done).length} / ${subtasks.length} complete</small></div><div class="timed-subtask-list">${visible.length ? visible.map((item) => `<div class="timed-subtask ${item.done ? 'done' : ''}"><button class="task-check" data-timed-subtask="${item.id}">${item.done ? '✓' : ''}</button><div><span>${escapeHtml(item.title)}</span><small>${item.done ? 'Completed' : item.status === 'overdue' ? 'Overdue' : formatRemaining(item.remaining_seconds)}</small></div><div class="subgoal-actions"><button class="mini-action" data-edit-timed-subtask="${item.id}" aria-label="Edit subtask">Edit</button><button class="mini-action" data-move-timed-subtask="${item.id}" data-direction="-1" aria-label="Move subtask up">↑</button><button class="mini-action" data-move-timed-subtask="${item.id}" data-direction="1" aria-label="Move subtask down">↓</button><button class="remove-task" data-remove-timed-subtask="${item.id}">×</button></div></div>`).join('') : '<p class="subtask-empty">Break this goal into smaller timed moves.</p>'}</div>${subtasks.length > 5 ? `<button class="subtask-toggle" data-toggle-timed-subtask-list="${goal.id}" type="button">${goal.expanded ? 'Show fewer' : `Show all (${subtasks.length})`}</button>` : ''}<form class="timed-subtask-form" data-timed-goal="${goal.id}"><input name="title" required placeholder="Subtask name"><input name="deadline" type="datetime-local" required><button type="submit">+</button></form></article>`; }
function bindTimedButtons(kind) { $('show-timed-form').addEventListener('click', () => $('timed-goal-form').classList.toggle('hidden')); $('timed-goal-form').addEventListener('submit', (event) => addTimedGoal(event, kind)); document.querySelectorAll('[data-remove-timed]').forEach((button) => button.addEventListener('click', () => removeTimedGoal(Number(button.dataset.removeTimed)))); document.querySelectorAll('[data-toggle-timed]').forEach((button) => button.addEventListener('click', () => toggleTimedGoal(Number(button.dataset.toggleTimed)))); document.querySelectorAll('[data-timed-subtask]').forEach((button) => button.addEventListener('click', () => toggleTimedSubtask(Number(button.dataset.timedSubtask)))); document.querySelectorAll('[data-remove-timed-subtask]').forEach((button) => button.addEventListener('click', () => removeTimedSubtask(Number(button.dataset.removeTimedSubtask)))); document.querySelectorAll('[data-edit-timed-subtask]').forEach((button) => button.addEventListener('click', () => editTimedSubtask(Number(button.dataset.editTimedSubtask)))); document.querySelectorAll('[data-move-timed-subtask]').forEach((button) => button.addEventListener('click', () => moveTimedSubtask(Number(button.dataset.moveTimedSubtask), Number(button.dataset.direction)))); document.querySelectorAll('[data-toggle-timed-subtask-list]').forEach((button) => button.addEventListener('click', () => toggleTimedSubtaskList(Number(button.dataset.toggleTimedSubtaskList)))); document.querySelectorAll('[data-toggle-completed-timed]').forEach((button) => button.addEventListener('click', () => toggleCompletedTimed(Number(button.dataset.toggleCompletedTimed)))); document.querySelectorAll('.timed-subtask-form').forEach((form) => form.addEventListener('submit', addTimedSubtask)); }
async function addTimedGoal(event, kind) { event.preventDefault(); const form = new FormData(event.target); try { state.data = await api(`/timed-goals/${kind}`, { method: 'POST', body: JSON.stringify(Object.fromEntries(form.entries())) }); renderPage(); } catch (error) { $('timed-message').textContent = error.message; } }
async function removeTimedGoal(id) { try { state.data = await api(`/timed-goals/${id}`, { method: 'DELETE' }); renderPage(); } catch (error) { $('timed-message').textContent = error.message; } }
async function toggleTimedGoal(id) { const goal = state.data.timed_goals.find((item) => item.id === id); try { state.data = await api(`/timed-goals/${id}`, { method: 'PUT', body: JSON.stringify({ done: !goal.done }) }); renderPage(); } catch (error) { $('timed-message').textContent = error.message; } }
async function addTimedSubtask(event) { event.preventDefault(); const form = new FormData(event.target); try { state.data = await api(`/timed-goals/${event.target.dataset.timedGoal}/subtasks`, { method: 'POST', body: JSON.stringify(Object.fromEntries(form.entries())) }); renderPage(); } catch (error) { $('timed-message').textContent = error.message; } }
async function toggleTimedSubtask(id) { const goal = state.data.timed_goals.find((item) => item.subtasks.some((subtask) => subtask.id === id)); const subtask = goal.subtasks.find((item) => item.id === id); try { state.data = await api(`/timed-subtasks/${id}`, { method: 'PUT', body: JSON.stringify({ done: !subtask.done }) }); renderPage(); } catch (error) { $('timed-message').textContent = error.message; } }
function toggleTimedSubtaskList(goalId) {
  const goal = state.data.timed_goals.find((item) => item.id === goalId);
  if (!goal) return;
  goal.expanded = !goal.expanded;
  renderPage();
}
async function editTimedSubtask(id) {
  const goal = state.data.timed_goals.find((item) => item.subtasks.some((subtask) => subtask.id === id));
  const subtask = goal?.subtasks.find((item) => item.id === id);
  if (!subtask) return;
  const nextTitle = window.prompt('Edit your subtask', subtask.title);
  if (nextTitle === null) return;
  const title = nextTitle.trim();
  if (!title) {
    $('timed-message').textContent = 'Give your subtask a title';
    return;
  }
  try {
    state.data = await api(`/timed-subtasks/${id}`, { method: 'PUT', body: JSON.stringify({ title }) });
    renderPage();
  } catch (error) {
    $('timed-message').textContent = error.message;
  }
}
async function moveTimedSubtask(id, direction) {
  const goal = state.data.timed_goals.find((item) => item.subtasks.some((subtask) => subtask.id === id));
  if (!goal) return;
  const index = goal.subtasks.findIndex((item) => item.id === id);
  if (index < 0) return;
  const targetIndex = index + direction;
  if (targetIndex < 0 || targetIndex >= goal.subtasks.length) return;
  try {
    state.data = await api(`/timed-subtasks/${id}`, { method: 'PUT', body: JSON.stringify({ order: targetIndex }) });
    renderPage();
  } catch (error) {
    $('timed-message').textContent = error.message;
  }
}
async function removeTimedSubtask(id) { try { state.data = await api(`/timed-subtasks/${id}`, { method: 'DELETE' }); renderPage(); } catch (error) { $('timed-message').textContent = error.message; } }
async function addMonthlyGoal(event) { event.preventDefault(); const form = new FormData(event.target); try { state.data = await api('/monthly-goals', { method: 'POST', body: JSON.stringify(Object.fromEntries(form.entries())) }); renderPage(); } catch (error) { $('month-message').textContent = error.message; } }
async function removeMonthlyGoal(id) { try { state.data = await api(`/monthly-goals/${id}`, { method: 'DELETE' }); renderPage(); } catch (error) { $('month-message').textContent = error.message; } }
async function addSubgoal(event) { event.preventDefault(); const form = new FormData(event.target); try { state.data = await api(`/monthly-goals/${event.target.dataset.goal}/subgoals`, { method: 'POST', body: JSON.stringify(Object.fromEntries(form.entries())) }); renderPage(); } catch (error) { $('month-message').textContent = error.message; } }
async function toggleSubgoal(id) { const goal = state.data.monthly_goals.find((item) => item.subgoals.some((subgoal) => subgoal.id === id)); const item = goal.subgoals.find((subgoal) => subgoal.id === id); try { state.data = await api(`/monthly-subgoals/${id}`, { method: 'PUT', body: JSON.stringify({ done: !item.done }) }); renderPage(); } catch (error) { $('month-message').textContent = error.message; } }
function toggleGoalSubtaskList(goalId) {
  const goal = state.data.monthly_goals.find((item) => item.id === goalId);
  if (!goal) return;
  goal.expanded = !goal.expanded;
  renderPage();
}
async function editSubgoal(id) {
  const goal = state.data.monthly_goals.find((item) => item.subgoals.some((subgoal) => subgoal.id === id));
  const subgoal = goal?.subgoals.find((item) => item.id === id);
  if (!subgoal) return;
  const nextTitle = window.prompt('Edit your subgoal', subgoal.title);
  if (nextTitle === null) return;
  const title = nextTitle.trim();
  if (!title) {
    $('month-message').textContent = 'Give your subgoal a title';
    return;
  }
  try {
    state.data = await api(`/monthly-subgoals/${id}`, { method: 'PUT', body: JSON.stringify({ title }) });
    renderPage();
  } catch (error) {
    $('month-message').textContent = error.message;
  }
}
async function moveSubgoal(id, direction) {
  const goal = state.data.monthly_goals.find((item) => item.subgoals.some((subgoal) => subgoal.id === id));
  if (!goal) return;
  const index = goal.subgoals.findIndex((item) => item.id === id);
  if (index < 0) return;
  const targetIndex = index + direction;
  if (targetIndex < 0 || targetIndex >= goal.subgoals.length) return;
  try {
    state.data = await api(`/monthly-subgoals/${id}`, { method: 'PUT', body: JSON.stringify({ order: targetIndex }) });
    renderPage();
  } catch (error) {
    $('month-message').textContent = error.message;
  }
}
async function removeSubgoal(id) { try { state.data = await api(`/monthly-subgoals/${id}`, { method: 'DELETE' }); renderPage(); } catch (error) { $('month-message').textContent = error.message; } }
function bindSectorButtons() { document.querySelectorAll('.task-check').forEach((button) => button.addEventListener('click', () => toggleSector(button.dataset.sector, Number(button.dataset.task)))); document.querySelector('[data-note]')?.addEventListener('click', () => saveNote(document.querySelector('[data-note]').dataset.note)); }
async function toggleTask(index) { const task = state.data.tasks[index]; task.done = !task.done; renderPage(); try { state.data = await api(`/progress/${index}`, { method: 'PUT', body: JSON.stringify({ done: task.done }) }); renderPage(); } catch (error) { $('page-message').textContent = error.message; } }
async function addDailyTask(event) { event.preventDefault(); const form = new FormData(event.target); try { state.data = await api('/daily-tasks', { method: 'POST', body: JSON.stringify(Object.fromEntries(form.entries())) }); renderPage(); } catch (error) { $('daily-message').textContent = error.message; } }
async function toggleDailyTask(id) { const task = state.data.daily_tasks.find((item) => item.id === id); try { state.data = await api(`/daily-tasks/${id}`, { method: 'PUT', body: JSON.stringify({ done: !task.done }) }); renderPage(); } catch (error) { $('daily-message').textContent = error.message; } }
async function removeDailyTask(id) { try { state.data = await api(`/daily-tasks/${id}`, { method: 'DELETE' }); renderPage(); } catch (error) { $('daily-message').textContent = error.message; } }
async function toggleSector(sector, index) { const items = state.data.sectors[sector] || []; items[index] = { done: !items[index]?.done }; renderPage(); try { state.data = await api(`/sectors/${sector}/${index}`, { method: 'PUT', body: JSON.stringify({ done: items[index].done }) }); renderPage(); } catch (error) { $('page-message').textContent = error.message; } }
async function saveNote(sector) { try { await api('/notes', { method: 'POST', body: JSON.stringify({ content: $('sector-note').value, sector }) }); $('page-message').textContent = 'Note saved.'; } catch (error) { $('page-message').textContent = error.message; } }
async function loadDashboard() { try { state.data = await api('/me/dashboard'); $('auth-view').classList.add('hidden'); $('app-view').classList.remove('hidden'); $('user-name'); $('page-greeting').textContent = `Good morning, ${state.data.user.name.split(' ')[0]}.`; $('avatar').textContent = state.data.user.name[0].toUpperCase(); $('sidebar-streak').textContent = `${state.data.streak} day${state.data.streak === 1 ? '' : 's'} streak`; syncPageHeader(); renderPage(); } catch { logout(); } }
async function logout() { try { await fetch('/api/auth/logout', { method: 'POST' }); } catch {} sessionStorage.removeItem('daymark_token'); localStorage.removeItem('daymark_token'); state.token = null; $('app-view').classList.add('hidden'); $('auth-view').classList.remove('hidden'); syncPageHeader(); }
function setDailyFilter(filter) { state.dailyFilter = filter; renderDaily(); }
function dailyTaskCard(task, index) { return `<article class="daily-board-task ${task.done ? 'done' : ''}" style="--task-index:${index}"><button class="daily-check task-check ${task.done ? 'is-complete' : ''}" data-daily-task="${task.id}" aria-label="${task.done ? 'Reopen' : 'Complete'} ${escapeHtml(task.name)}">${task.done ? '✓' : ''}</button><div class="daily-board-task-main"><div class="daily-board-task-meta"><span class="daily-task-number">${String(index + 1).padStart(2, '0')}</span><span class="task-type">${escapeHtml(task.type)}</span><span class="daily-board-time">${escapeHtml(task.time)}</span></div><strong>${escapeHtml(task.name)}</strong><p>${escapeHtml(task.motive)}</p></div><button class="daily-board-remove remove-task" data-remove-task="${task.id}" aria-label="Remove ${escapeHtml(task.name)}">×</button></article>`; }
function renderDaily() { const tasks = state.data.daily_tasks || []; const completed = tasks.filter((task) => task.done); const open = tasks.filter((task) => !task.done); const filter = state.dailyFilter || 'open'; const visible = filter === 'done' ? completed : filter === 'all' ? tasks : open; const progress = progressPercent(tasks); $('page-container').innerHTML = `<section class="daily-command"><div><p class="eyebrow">${state.data.date_label}</p><h2>Today is yours<br><em>to arrange.</em></h2><p class="muted hero-copy">A flexible board for the things that make today count. Keep the next move close.</p></div><div class="daily-score"><div class="daily-score-ring"><strong>${progress}%</strong><span>complete</span></div><small>${open.length} open · ${completed.length} done</small></div></section><section class="daily-board"><div class="daily-board-head"><div><p class="eyebrow">Your today board</p><h3>${open.length ? `${open.length} moves left` : 'Everything is checked off'}</h3></div><div class="daily-filters"><button class="daily-filter ${filter === 'open' ? 'active' : ''}" data-daily-filter="open">Open <span>${open.length}</span></button><button class="daily-filter ${filter === 'all' ? 'active' : ''}" data-daily-filter="all">All <span>${tasks.length}</span></button><button class="daily-filter ${filter === 'done' ? 'active' : ''}" data-daily-filter="done">Done <span>${completed.length}</span></button></div></div><div class="daily-board-list">${visible.length ? visible.map((task, index) => dailyTaskCard(task, index)).join('') : `<div class="daily-empty-state"><strong>${filter === 'done' ? 'Nothing completed yet.' : 'You are clear.'}</strong><span>${filter === 'done' ? 'Finish a move and it will land here.' : 'Add a task or enjoy the empty space.'}</span></div>`}</div></section><aside class="daily-add-panel"><div><p class="eyebrow">Add to today</p><h3>Give your time a job.</h3><p>Make it specific enough to start before motivation arrives.</p></div><form id="daily-task-form"><label>Task name<input name="name" required placeholder="e.g. Finish graph revision"></label><label>Type<select name="type"><option>Deep work</option><option>Study</option><option>Health</option><option>Personal</option><option>Admin</option></select></label><div class="form-split"><label>Time<input name="time" required placeholder="09:00 - 10:30"></label><label>Motive<input name="motive" required placeholder="Why it matters"></label></div><button class="button button-dark" type="submit">Add move <span>+</span></button><p id="daily-message" class="form-message"></p></form></aside>`; bindDailyButtons(); document.querySelectorAll('[data-daily-filter]').forEach((button) => button.addEventListener('click', () => setDailyFilter(button.dataset.dailyFilter))); renderDailyAnalysis(); }
function subtaskActionButtons(item, timed) { const editAttribute = timed ? 'data-edit-timed-subtask' : 'data-edit-subgoal'; const moveAttribute = timed ? 'data-move-timed-subtask' : 'data-move-subgoal'; const removeAttribute = timed ? 'data-remove-timed-subtask' : 'data-remove-subgoal'; return `<div class="subgoal-actions"><button class="mini-action" ${editAttribute}="${item.id}" aria-label="Edit subtask">Edit</button>${!item.done ? `<button class="mini-action" ${moveAttribute}="${item.id}" data-direction="-1" aria-label="Move subtask up">↑</button><button class="mini-action" ${moveAttribute}="${item.id}" data-direction="1" aria-label="Move subtask down">↓</button>` : ''}<button class="remove-task" ${removeAttribute}="${item.id}" aria-label="Remove subtask">×</button></div>`; }
function toggleCompletedMonth(goalId) { const goal = state.data.monthly_goals.find((item) => item.id === goalId); if (!goal) return; goal.completedExpanded = !goal.completedExpanded; renderPage(); }
function toggleCompletedTimed(goalId) { const goal = state.data.timed_goals.find((item) => item.id === goalId); if (!goal) return; goal.completedExpanded = !goal.completedExpanded; renderPage(); }
function completedToggle(goalId, count, expanded, timed) { const attribute = timed ? 'data-toggle-completed-timed' : 'data-toggle-completed-month'; return `<button class="completed-toggle" ${attribute}="${goalId}" type="button">${expanded ? 'Hide' : 'Show'} completed (${count})</button>`; }
function completedRows(items, timed) { return items.map((item) => timed ? `<div class="timed-subtask completed"><button class="task-check is-complete" data-timed-subtask="${item.id}" aria-label="Reopen ${escapeHtml(item.title)}">✓</button><div><span>${escapeHtml(item.title)}</span><small>Completed</small></div>${subtaskActionButtons(item, true)}</div>` : `<div class="subgoal-row completed"><button class="task-check is-complete" data-subgoal="${item.id}" aria-label="Reopen ${escapeHtml(item.title)}">✓</button><span>${escapeHtml(item.title)}</span>${subtaskActionButtons(item, false)}</div>`).join(''); }
function collapseCompletedSections() { document.querySelectorAll('.completed-subtasks').forEach((section) => { const heading = section.querySelector('.completed-heading'); if (!heading || section.querySelector('.completed-toggle')) return; const rows = [...section.children].filter((child) => child !== heading); rows.forEach((row) => row.classList.add('completed-hidden')); const button = document.createElement('button'); button.className = 'completed-toggle'; button.type = 'button'; button.textContent = `Show completed (${rows.length})`; button.addEventListener('click', () => { const expanded = button.dataset.expanded === 'true'; rows.forEach((row) => row.classList.toggle('completed-hidden', expanded)); button.dataset.expanded = String(!expanded); button.textContent = `${expanded ? 'Show' : 'Hide'} completed (${rows.length})`; }); section.insertBefore(button, heading); }); }
function goalSubtaskBoardCard(item, index, timed) { const status = item.done ? 'completed' : timed && item.status === 'overdue' ? 'overdue' : 'open'; const label = timed ? (item.done ? 'Completed' : item.status === 'overdue' ? 'Overdue' : formatRemaining(item.remaining_seconds)) : 'Monthly move'; const editAttribute = timed ? 'data-edit-timed-subtask' : 'data-edit-subgoal'; const moveAttribute = timed ? 'data-move-timed-subtask' : 'data-move-subgoal'; const removeAttribute = timed ? 'data-remove-timed-subtask' : 'data-remove-subgoal'; const toggleAttribute = timed ? 'data-timed-subtask' : 'data-subgoal'; return `<article class="daily-board-task subtask-board-card ${status}" style="--task-index:${index}"><button class="daily-check task-check ${item.done ? 'is-complete' : ''}" ${toggleAttribute}="${item.id}" aria-label="${item.done ? 'Reopen' : 'Complete'} ${escapeHtml(item.title)}">${item.done ? '✓' : ''}</button><div class="daily-board-task-main"><div class="daily-board-task-meta"><span class="daily-task-number">${String(index + 1).padStart(2, '0')}</span><span class="task-type">${timed ? 'Timed move' : 'Subtask'}</span><span class="daily-board-time">${escapeHtml(label)}</span></div><strong>${escapeHtml(item.title)}</strong><p>${item.done ? 'Completed and saved.' : timed ? 'Keep this move visible and moving.' : 'One clear move toward the goal.'}</p></div><div class="subgoal-actions subtask-card-actions"><button class="mini-action" ${editAttribute}="${item.id}" aria-label="Edit subtask">Edit</button>${!item.done ? `<button class="mini-action" ${moveAttribute}="${item.id}" data-direction="-1" aria-label="Move subtask up">↑</button><button class="mini-action" ${moveAttribute}="${item.id}" data-direction="1" aria-label="Move subtask down">↓</button>` : ''}<button class="remove-task" ${removeAttribute}="${item.id}" aria-label="Remove subtask">×</button></div></article>`; }
function monthGoalCard(goal) { const open = goal.subgoals.filter((item) => !item.done); const completedItems = goal.subgoals.filter((item) => item.done); const visible = goal.expanded ? open : open.slice(0, 5); const percent = goal.subgoals.length ? Math.round(completedItems.length / goal.subgoals.length * 100) : 0; return `<article class="month-goal-card"><div class="goal-card-head"><div><span class="goal-number">GOAL 0${goal.id} · <b class="status-${goal.status}">${goal.status}</b></span><h3>${escapeHtml(goal.title)}</h3><p>${escapeHtml(goal.motive || 'A result worth showing up for.')}</p></div><div class="goal-card-actions"><strong>${percent}%</strong><button class="remove-task" data-remove-goal="${goal.id}" aria-label="Remove goal">×</button></div></div><div class="goal-meter"><span style="width:${percent}%"></span></div><div class="subgoal-heading"><span>${goal.expanded ? 'Open moves' : 'Next moves'}</span><small>${completedItems.length} complete · ${goal.subgoals.length} total</small></div><div class="subgoal-list subtask-board-list">${visible.length ? visible.map((item, index) => goalSubtaskBoardCard(item, index, false)).join('') : '<p class="subgoal-empty">All moves are complete. Add another subgoal to continue.</p>'}</div>${completedItems.length ? `<div class="completed-subtasks"><div class="completed-heading">Completed <span>${completedItems.length}</span></div>${completedItems.map((item, index) => goalSubtaskBoardCard(item, index, false)).join('')}</div>` : ''}${goal.subgoals.length > 5 ? `<button class="subtask-toggle" data-toggle-subgoal-list="${goal.id}" type="button">${goal.expanded ? 'Show fewer open' : `Show all open (${open.length})`}</button>` : ''}<form class="subgoal-form" data-goal="${goal.id}"><input name="title" required placeholder="Add a subgoal"><button type="submit" aria-label="Add subgoal">+</button></form></article>`; }
function timedGoalCard(goal) { const subtasks = goal.subtasks || []; const open = subtasks.filter((item) => !item.done); const completedItems = subtasks.filter((item) => item.done); const visible = goal.expanded ? open : open.slice(0, 5); return `<article class="timed-goal-card ${goal.status}"><div class="timed-card-top"><span class="goal-number">${goal.status}</span><button class="remove-task" data-remove-timed="${goal.id}" aria-label="Remove goal">×</button></div><h3>${escapeHtml(goal.title)}</h3><p>${escapeHtml(goal.motive || 'A goal worth protecting.')}</p><div class="countdown ${goal.status}">${goal.done ? 'Completed' : goal.status === 'overdue' ? 'Overdue' : formatRemaining(goal.remaining_seconds)}</div><div class="timed-card-actions"><button class="button ${goal.done ? 'button-light' : 'button-dark'}" data-toggle-timed="${goal.id}">${goal.done ? 'Reopen goal' : 'Mark complete'} <span>✓</span></button><small>${goal.elapsed_percent}% of planned time used</small></div><div class="subtask-heading"><span>${goal.expanded ? 'Open subtasks' : 'Next subtasks'}</span><small>${completedItems.length} / ${subtasks.length} complete</small></div><div class="timed-subtask-list subtask-board-list">${visible.length ? visible.map((item, index) => goalSubtaskBoardCard(item, index, true)).join('') : '<p class="subtask-empty">All subtasks are complete. Add another timed move.</p>'}</div>${completedItems.length ? `<div class="completed-subtasks"><div class="completed-heading">Completed <span>${completedItems.length}</span></div>${completedItems.map((item, index) => goalSubtaskBoardCard(item, index, true)).join('')}</div>` : ''}${subtasks.length > 5 ? `<button class="subtask-toggle" data-toggle-timed-subtask-list="${goal.id}" type="button">${goal.expanded ? 'Show fewer open' : `Show all open (${open.length})`}</button>` : ''}<form class="timed-subtask-form" data-timed-goal="${goal.id}"><input name="title" required placeholder="Add a timed subtask"><input name="deadline" type="datetime-local" required><button type="submit" aria-label="Add timed subtask">+</button></form></article>`; }
function renderPage() { syncPageHeader(); const page = location.hash.slice(1) || 'home'; document.querySelectorAll('.nav-link').forEach((link) => link.classList.toggle('active', link.dataset.page === page)); if (page === 'home') renderHome(); else if (page === 'daily') renderDaily(); else if (page === 'month') renderMonth(); else if (page === 'temporary' || page === 'longterm') renderTimedGoals(page); else if (sectors[page]) { $('page-container').innerHTML = pageFrame(page, []); bindSectorButtons(); } else { location.hash = '#home'; } moveCompletedGoalsToArchive(page); collapseCompletedSections(); }
function moveCompletedGoalsToArchive(page) {
  const isMonthly = page === 'month';
  if (!isMonthly && page !== 'temporary' && page !== 'longterm') return;
  const grid = document.querySelector(isMonthly ? '.goal-stack' : '.timed-goal-grid');
  if (!grid) return;
  const goals = isMonthly ? state.data.monthly_goals || [] : (state.data.timed_goals || []).filter((goal) => goal.kind === page);
  const completed = goals.filter((goal) => isMonthly ? goal.status === 'completed' : goal.done);
  const cards = completed.map((goal) => grid.querySelector(`[data-remove-${isMonthly ? 'goal' : 'timed'}="${goal.id}"]`)?.closest(isMonthly ? '.month-goal-card' : '.timed-goal-card')).filter(Boolean);
  if (!cards.length) return;
  const archive = document.createElement('section');
  archive.className = 'completed-goals-block';
  archive.innerHTML = `<div class="completed-goals-heading"><p class="eyebrow">Finished work</p><h3>Completed goals <span>${cards.length}</span></h3></div><div class="completed-goal-list"></div>`;
  cards.forEach((card) => archive.querySelector('.completed-goal-list').appendChild(card));
  if (!grid.querySelector(isMonthly ? '.month-goal-card' : '.timed-goal-card')) {
    grid.innerHTML = '<div class="empty-goals">No pending goals. Add a new goal to keep moving.</div>';
  }
  $('page-container').appendChild(archive);
}
function monthGoalCard(goal) { const open = goal.subgoals.filter((item) => !item.done); const completedItems = goal.subgoals.filter((item) => item.done); const visible = goal.expanded ? open : open.slice(0, 5); const percent = goal.subgoals.length ? Math.round(completedItems.length / goal.subgoals.length * 100) : 0; return `<article class="month-goal-card"><div class="goal-card-head"><div><span class="goal-number">GOAL 0${goal.id} · <b class="status-${goal.status}">${goal.status}</b></span><h3>${escapeHtml(goal.title)}</h3><p>${escapeHtml(goal.motive || 'A result worth showing up for.')}</p></div><div class="goal-card-actions"><strong>${percent}%</strong><button class="remove-task" data-remove-goal="${goal.id}" aria-label="Remove goal">×</button></div></div><div class="goal-meter"><span style="width:${percent}%"></span></div><div class="subgoal-heading"><span>${goal.expanded ? 'Open moves' : 'Next moves'}</span><small>${completedItems.length} complete · ${goal.subgoals.length} total</small></div><div class="subgoal-list">${visible.length ? visible.map((item) => `<div class="subgoal-row"><button class="task-check" data-subgoal="${item.id}" aria-label="Complete ${escapeHtml(item.title)}"></button><span>${escapeHtml(item.title)}</span>${subtaskActionButtons(item, false)}</div>`).join('') : '<p class="subgoal-empty">All moves are complete. Add another subgoal to continue.</p>'}</div>${completedItems.length ? `<div class="completed-subtasks"><div class="completed-heading">Completed <span>${completedItems.length}</span></div>${completedItems.map((item) => `<div class="subgoal-row completed"><button class="task-check is-complete" data-subgoal="${item.id}" aria-label="Reopen ${escapeHtml(item.title)}">✓</button><span>${escapeHtml(item.title)}</span>${subtaskActionButtons(item, false)}</div>`).join('')}</div>` : ''}${goal.subgoals.length > 5 ? `<button class="subtask-toggle" data-toggle-subgoal-list="${goal.id}" type="button">${goal.expanded ? 'Show fewer open' : `Show all open (${open.length})`}</button>` : ''}<form class="subgoal-form" data-goal="${goal.id}"><input name="title" required placeholder="Add a subgoal"><button type="submit" aria-label="Add subgoal">+</button></form></article>`; }
function timedGoalCard(goal) { const subtasks = goal.subtasks || []; const open = subtasks.filter((item) => !item.done); const completedItems = subtasks.filter((item) => item.done); const visible = goal.expanded ? open : open.slice(0, 5); return `<article class="timed-goal-card ${goal.status}"><div class="timed-card-top"><span class="goal-number">${goal.status}</span><button class="remove-task" data-remove-timed="${goal.id}" aria-label="Remove goal">×</button></div><h3>${escapeHtml(goal.title)}</h3><p>${escapeHtml(goal.motive || 'A goal worth protecting.')}</p><div class="countdown ${goal.status}">${goal.done ? 'Completed' : goal.status === 'overdue' ? 'Overdue' : formatRemaining(goal.remaining_seconds)}</div><div class="timed-card-actions"><button class="button ${goal.done ? 'button-light' : 'button-dark'}" data-toggle-timed="${goal.id}">${goal.done ? 'Reopen goal' : 'Mark complete'} <span>✓</span></button><small>${goal.elapsed_percent}% of planned time used</small></div><div class="subtask-heading"><span>${goal.expanded ? 'Open subtasks' : 'Next subtasks'}</span><small>${completedItems.length} / ${subtasks.length} complete</small></div><div class="timed-subtask-list">${visible.length ? visible.map((item) => `<div class="timed-subtask"><button class="task-check" data-timed-subtask="${item.id}" aria-label="Complete ${escapeHtml(item.title)}"></button><div><span>${escapeHtml(item.title)}</span><small>${item.status === 'overdue' ? 'Overdue' : formatRemaining(item.remaining_seconds)}</small></div>${subtaskActionButtons(item, true)}</div>`).join('') : '<p class="subtask-empty">All subtasks are complete. Add another timed move.</p>'}</div>${completedItems.length ? `<div class="completed-subtasks"><div class="completed-heading">Completed <span>${completedItems.length}</span></div>${completedItems.map((item) => `<div class="timed-subtask completed"><button class="task-check is-complete" data-timed-subtask="${item.id}" aria-label="Reopen ${escapeHtml(item.title)}">✓</button><div><span>${escapeHtml(item.title)}</span><small>Completed</small></div>${subtaskActionButtons(item, true)}</div>`).join('')}</div>` : ''}${subtasks.length > 5 ? `<button class="subtask-toggle" data-toggle-timed-subtask-list="${goal.id}" type="button">${goal.expanded ? 'Show fewer open' : `Show all open (${open.length})`}</button>` : ''}<form class="timed-subtask-form" data-timed-goal="${goal.id}"><input name="title" required placeholder="Add a timed subtask"><input name="deadline" type="datetime-local" required><button type="submit" aria-label="Add timed subtask">+</button></form></article>`; }
function monthGoalCard(goal) { const open = goal.subgoals.filter((item) => !item.done); const completedItems = goal.subgoals.filter((item) => item.done); const visible = goal.expanded ? open : open.slice(0, 5); const percent = goal.subgoals.length ? Math.round(completedItems.length / goal.subgoals.length * 100) : 0; return `<article class="month-goal-card"><div class="goal-card-head"><div><span class="goal-number">GOAL 0${goal.id} · <b class="status-${goal.status}">${goal.status}</b></span><h3>${escapeHtml(goal.title)}</h3><p>${escapeHtml(goal.motive || 'A result worth showing up for.')}</p></div><div class="goal-card-actions"><strong>${percent}%</strong><button class="remove-task" data-remove-goal="${goal.id}" aria-label="Remove goal">×</button></div></div><div class="goal-meter"><span style="width:${percent}%"></span></div><div class="subgoal-heading"><span>${goal.expanded ? 'Open moves' : 'Next moves'}</span><small>${completedItems.length} complete · ${goal.subgoals.length} total</small></div><div class="subgoal-list subtask-board-list">${visible.length ? visible.map((item, index) => goalSubtaskBoardCard(item, index, false)).join('') : '<p class="subgoal-empty">All moves are complete. Add another subgoal to continue.</p>'}</div>${completedItems.length ? `<div class="completed-subtasks"><div class="completed-heading">Completed <span>${completedItems.length}</span></div>${completedItems.map((item, index) => goalSubtaskBoardCard(item, index, false)).join('')}</div>` : ''}${goal.subgoals.length > 5 ? `<button class="subtask-toggle" data-toggle-subgoal-list="${goal.id}" type="button">${goal.expanded ? 'Show fewer open' : `Show all open (${open.length})`}</button>` : ''}<form class="subgoal-form" data-goal="${goal.id}"><input name="title" required placeholder="Add a subgoal"><button type="submit" aria-label="Add subgoal">+</button></form></article>`; }
function timedGoalCard(goal) { const subtasks = goal.subtasks || []; const open = subtasks.filter((item) => !item.done); const completedItems = subtasks.filter((item) => item.done); const visible = goal.expanded ? open : open.slice(0, 5); return `<article class="timed-goal-card ${goal.status}"><div class="timed-card-top"><span class="goal-number">${goal.status}</span><button class="remove-task" data-remove-timed="${goal.id}" aria-label="Remove goal">×</button></div><h3>${escapeHtml(goal.title)}</h3><p>${escapeHtml(goal.motive || 'A goal worth protecting.')}</p><div class="countdown ${goal.status}">${goal.done ? 'Completed' : goal.status === 'overdue' ? 'Overdue' : formatRemaining(goal.remaining_seconds)}</div><div class="timed-card-actions"><button class="button ${goal.done ? 'button-light' : 'button-dark'}" data-toggle-timed="${goal.id}">${goal.done ? 'Reopen goal' : 'Mark complete'} <span>✓</span></button><small>${goal.elapsed_percent}% of planned time used</small></div><div class="subtask-heading"><span>${goal.expanded ? 'Open subtasks' : 'Next subtasks'}</span><small>${completedItems.length} / ${subtasks.length} complete</small></div><div class="timed-subtask-list subtask-board-list">${visible.length ? visible.map((item, index) => goalSubtaskBoardCard(item, index, true)).join('') : '<p class="subtask-empty">All subtasks are complete. Add another timed move.</p>'}</div>${completedItems.length ? `<div class="completed-subtasks"><div class="completed-heading">Completed <span>${completedItems.length}</span></div>${completedItems.map((item, index) => goalSubtaskBoardCard(item, index, true)).join('')}</div>` : ''}${subtasks.length > 5 ? `<button class="subtask-toggle" data-toggle-timed-subtask-list="${goal.id}" type="button">${goal.expanded ? 'Show fewer open' : `Show all open (${open.length})`}</button>` : ''}<form class="timed-subtask-form" data-timed-goal="${goal.id}"><input name="title" required placeholder="Add a timed subtask"><input name="deadline" type="datetime-local" required><button type="submit" aria-label="Add timed subtask">+</button></form></article>`; }
document.querySelectorAll('.tab').forEach((tab) => tab.addEventListener('click', () => setAuthMode(tab.dataset.auth))); $('auth-form').addEventListener('submit', submitAuth); $('logout-button').addEventListener('click', logout); window.addEventListener('hashchange', renderPage); if (state.token) loadDashboard();
